Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "E:\my_project\navigator\navigator_window.py", line 169, in runCommand
    psend(cmd)
  File "E:\my_project\navigator\navigator_window.py", line 31, in psend
    meter.anyCmd()
  File "E:\my_project\navigator\encap_cmd.py", line 86, in anyCmd
    genFrame(code, data_len, fun_code, data)
NameError: name 'genFrame' is not defined
